name: rpg_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: "^2.0.0"
  sqflite: any
  provider: ^5.0.0
  syncfusion_flutter_charts: ^19.1.66+1

  cupertino_icons: ^1.0.2


dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.0

flutter_native_splash:
  color: "#ababab"
  image: "icon/sig-512.png"

flutter_icons:
    image_path: "icon/sig-512.png"
    android: true
    ios: true
flutter:

  uses-material-design: true